#!/bin/bash
#Script that installs Nginx web server and sets it up to return a "Hello World!" message

#Update installed packages
sudo apt-get update

#Install nginx if it's not already installed
if [ ! -x /usr/sbin/nginx ]; then
    sudo apt-get install nginx -y
fi

#Start nginx if it's not already running
if [ $(service nginx status | grep -o "not" | wc -l) -eq 1 ]; then
        sudo service nginx start
fi

#Configure nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

#Restart nginx
sudo killall nginx
sudo nginx -g 'daemon off;'
#We can't use systemctl for restarting nginx in the current environment, that's why we're using kill all and starting it manually
