#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80 from port 8080
cp -r /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
pkill -o nginx
